<a href="https://colab.research.google.com/github/siddhidamkondwar/Statistics-/blob/main/stat_31_05_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import linalg
import scipy
from scipy import stats
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm, t
from scipy.stats import expon
from collections import Counter
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

In [ ]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]

df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
model = ols('Resp~Factor1*Factor2',df).fit()
res=sm.stats.anova_lm(model)

In [ ]:
df

,Resp,Factor1,Factor2
0,34,1,R
1,43,1,D
2,57,1,R
3,40,1,D
4,85,2,R
5,68,2,D
6,67,2,R
7,53,2,D
8,41,3,R
9,24,3,D


In [ ]:
z and t test : when
2 sample t test : two indeepnedant sample s diiff of mean comaired against
paired: before - after
onw way ; response con data value of cat data has

# 1-sample z test/ 1 sample t test

This test is used to compare the sample mean of one sample sample against a calim value and establish whether their difference is statistically significant or not

# 2-sample t test

This test is used to compare the difference of means of two independent samples against a claim value and establish whether their difference is statistically significant or not

# Paired t test

This test is used when we have two paired samples. The average difference between the paired values is compared against a claim values and establish whether their difference is statistically significant or not
The key word here is before-after

# One way ANOVA

Used when we have multiple samples. This test compares all the pair of the means. It checks whether the difference of each pair of mean can be ignored or not OR can be considered to be equal to 0 or not.
The Ho in this case is that all the pair of means are equal

# Multi way ANOVA

Used when we have multiple factors influencing the response. IN addition to their individual effect, we would also like to study the interactions between various factors.

# 1-proportion test
This test is used to compare the proportion calculated from a sample against a claim value and establish whether their difference is statistically significant or not

In [ ]:
mu = 500*0.7

In [ ]:
mu

350.0

In [ ]:
sd = (500*0.7*0.3)**0.5

In [ ]:
sd

10.246950765959598

In [ ]:
binom.cdf(370,500,0.7) - binom.cdf(329,500,0.7)

np.float64(0.9547133734363867)

In [ ]:
norm.cdf(370,mu,sd) - norm.cdf(329.5,mu,sd)

np.float64(0.9518010131489951)

In [ ]:
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

In [ ]:
statsmodels.stats.proportion.proportions_ztest(180,400,0.4,alternative='larger')

(np.float64(2.0100756305184238), np.float64(0.022211592425003045))

In [ ]:
#pune CDAC claims that they have atleast 8% more engg as compaied

In [ ]:
#Ho pr(pune) - pr(kharghar) >= 0.08
#Ha pr(pune) - pr(kharghar) < 0.08

In [ ]:
#In sample of 70 stuedents in pune 40 were btech
##In sample of 80 stuedents in kharghar 38 were btech

In [ ]:
40/70 - 38/80

0.09642857142857142

In [ ]:
40/70 - 48/80

-0.02857142857142858

In [ ]:
engg = np.array([40,48])

In [ ]:
total = np.array([70,80])

In [ ]:
statsmodels.stats.proportion.proportions_ztest(engg,total,0.08,alternative='smaller')

(np.float64(-1.3471563869719667), np.float64(0.08896493545619544))

# Chi square test for goodness of fit
Used when there are multiple categories. The counts obtained for each category would be compared aginst the claimed pattern to check whether the counts follow the pattern or not. The standard Ho is that the counts follow the pattern

In [ ]:
#Claimed pattern for the qualification

In [ ]:
#Btech - 0.4 Mtech - 0.1, MCA -0.3, Msc-0.2

In [ ]:
##Btech - 50, Mtech - 20, MCA -45, Msc-25

In [ ]:
#whether counts obtained from sample follow the pattern or not

In [ ]:
counts = np.array([50,20,45,25])

In [ ]:
pattern = np.array([0.4,0.1,0.3,0.2])

In [ ]:
exp_counts = sum(counts) * pattern

In [ ]:
exp_counts

array([56., 14., 42., 28.])

In [ ]:
from scipy.stats import chisquare

In [ ]:
scipy.stats.chisquare(counts, f_exp = exp_counts)

Power_divergenceResult(statistic=np.float64(3.7500000000000004), pvalue=np.float64(0.2897557811933843))

In [ ]:
sum((exp_counts - counts)**2/exp_counts)

np.float64(3.7500000000000004)

In [ ]:
(exp_counts - counts)**2/exp_counts

array([0.64285714, 2.57142857, 0.21428571, 0.32142857])

In [ ]:
counts = np.array([70,10,35,45])
exp_counts = sum(counts) * pattern
scipy.stats.chisquare(counts, f_exp = exp_counts)
# p-value<0.05, so we reject Ho

exp_counts
#Out[60]: array([64., 16., 48., 32.])

sum((exp_counts - counts)**2/exp_counts)
#Out[61]: np.float64(11.614583333333334)

(exp_counts - counts)**2/exp_counts
#Out[62]: array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

# Chi square test for degree pf association
Used when we wish to check and establish whether one categorical data has an effect on the other categorical data or not

Ho: categorical variable A does not influence the choice from categorical variable B

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
#three food soutn,maharastrian,Gujarati

In [ ]:
food = np.array([[45,70,60],[70,40,25]])

In [ ]:
food

array([[45, 70, 60],
       [70, 40, 25]])

In [ ]:
scipy.stats.chi2_contingency(food)

Chi2ContingencyResult(statistic=np.float64(23.25424258416586), pvalue=np.float64(8.920832446902749e-06), dof=2, expected_freq=array([[64.91935484, 62.09677419, 47.98387097],
       [50.08064516, 47.90322581, 37.01612903]]))